### ISSUE TITLE
* cough cough *

### ISSUE THREAD

**Issue by jdohgamer** [kingdaro/stream-overlay#1]
I had it in a random chrome tab for awhile. That single tab reached 800MB+ memory usaed. 😨 

https://www.useloom.com/share/99210b62194d4a0d9d905589cbb1346f

**Comment by itsMapleLeaf** [comment]
Yeah, there are probably hella memory leaks in the current implementation. I'll look into it. Thanks for the report 👍

**Comment by jdohgamer** [comment]
Of course! Actually stumbled upon it because I put it on my other monitor to watch it loop for a bit while I was gaming.

It really is a fantastic use of the technology! Great work, man! 🤩

**Comment by itsMapleLeaf** [comment]
Thanks! ❤️ 

I refactored the logic a bit, which should hopefully fix the memory leak. Let me know otherwise
